name: Publish and Deploy

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Create folder
        run: mkdir -p public

      - name: Output to HTML
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1
        with:
          source: index.bs
          destination: public/index.html

      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
